apiVersion: v1
kind: Service
metadata:
  name: mongo-server-nodeport-1
  namespace: linklab
spec:
  type: NodePort
  ports:
  - name: mongodb
    port: 27017
    nodePort: 31201
    protocol: TCP
    targetPort: mongodb
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo-server
    app.kubernetes.io/name: mongodb
    statefulset.kubernetes.io/pod-name: mongo-server-1
  sessionAffinity: None
