---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data-pvc
  namespace: linklab
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: log-data