apiVersion: v1
kind: PersistentVolume
metadata:
  name: linklab-compilev2-arduinomega-virtual-worker-writespace.0-pv
  namespace: linklab
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: linklab-compilev2-arduinomega-virtual-worker-writespace
  hostPath:
    path: /root/linklab-ldc/nfs/data/compile-worker/arduinomega-virtual-worker/writespace.0