apiVersion: v1
kind: Pod
metadata:
  name: ubuntu02
spec:
  containers:
  - name: ubuntu02
    image:  imagetest1
    imagePullPolicy: IfNotPresent
    args: ["/bin/bash","-c","while true; do date; sleep 1; done"]
