---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: influxdb-server
  namespace: linklab
spec:
  rules:
  - host: influxdb.testbd.tinylink.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: influxdb-server
          servicePort: 8086
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb-server
    namespace: linklab
    labels:
        app: influxdb-server
spec:
    selector:
        app: influxdb-server
    ports:
    - port: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: influxdb-server-data-pvc
    namespace: linklab
spec:
    accessModes:
    - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 20Gi
    storageClassName: nas
    selector:
        matchLabels:
            storage-class: influxdb-server-data
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: influxdb-server
    namespace: linklab
    labels:
        app: influxdb-server
spec:
    selector:
        matchLabels:
            app: influxdb-server
    serviceName: "influxdb-server"
    replicas: 1
    template:
        metadata:
            labels:
                app: influxdb-server
        spec:
            containers:
            - name: influxdb-server
              image: influxdb:1.8.2-alpine
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 8086
              envFrom:
              - configMapRef:
                    name: influxdb-server-env
              volumeMounts:
              - name: influxdb-server-config-volume
                mountPath: /etc/influxdb/influxdb.conf
                subPath: influxdb.conf
              - name: influxdb-server-config-volume
                mountPath: /docker-entrypoint-initdb.d/influxdb-init.iql
                subPath: influxdb-init.iql
              - name: influxdb-server-data-volume
                mountPath: /var/lib/influxdb
            volumes:
            - name: influxdb-server-config-volume
              configMap:
                name: influxdb-server-config
            - name: influxdb-server-data-volume
              persistentVolumeClaim:
                claimName: influxdb-server-data-pvc
