apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-server-data-0
  namespace: linklab
  labels:
    alicloud-pvname: influxdb-server-data-0
    storage-class: influxdb-server-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeAttributes:
      path: /nfs/data/influxdb/data-0
      server: 043944ae96-buv89.cn-hangzhou.nas.aliyuncs.com
      vers: '3'
    volumeHandle: influxdb-server-data-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem