apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-server-data-pv
  namespace: linklab
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: influxdb-server-data
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/home/kaikai/new-linklab/linklab-ldc/nfs/data/influxdb/data"
    server: 10.214.131.107
