apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-server-data-pv-2
  namespace: linklab
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-server-data
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/home/kaikai/new-linklab/linklab-ldc/nfs/data/redis/data-0"
    server: 10.214.131.107
