apiVersion: v1
kind: PersistentVolume
metadata:
  name: linklab-compilev2-esp32duino-virtual-worker-writespace.0-pv
  namespace: linklab
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: linklab-compilev2-esp32duino-virtual-worker-writespace
  hostPath:
    path: /home/yangg/Documents/code/go/linklab-ldc/nfs/data/compile-worker/esp32duino-virtual-worker/writespace.0