---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
# kubernetesVersion: v1.19.3
imageRepository: registry.aliyuncs.com/google_containers
networking:
  podSubnet: 10.244.0.0/16
# controlPlaneEndpoint: "10.214.149.214:6444"
controllerManager:
  extraArgs:
    horizontal-pod-autoscaler-sync-period: 5s
apiServer:
  extraArgs:
    advertise-address: 10.214.131.107
