apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-client
  namespace: linklab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-client
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces", "pods/log", "pods/exec", "services"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-client
  namespace: linklab
subjects:
- kind: ServiceAccount
  name: edge-client
  namespace: linklab
roleRef:
  kind: ClusterRole
  name: edge-client
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: edge-client
  namespace: linklab
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: edge-client
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: edge-client
  namespace: linklab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-client
  template:
    metadata:
      labels:
        app: edge-client
    spec:
      containers: 
      - name: edge-client
        image: registry.cn-hangzhou.aliyuncs.com/linklab/device-control-v2-edge-client:v2.0-beta
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: edge-client-config-volume
            mountPath: /app/config
          - name: edge-client-yaml-volume
            mountPath: /app/yaml
      serviceAccountName: edge-client
      volumes:
        - name: edge-client-config-volume
          configMap:
            name: edge-client-config
        - name: edge-client-yaml-volume
          configMap:
            name: edge-client-yaml
      imagePullSecrets:
        - name: linklab-aliyun
      nodeSelector:
        node-role.kubernetes.io/master: ""