apiVersion: v1
kind: Pod
metadata:
  name: cloud-test
  labels:
    app: cloud-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: cloud-test
    image: edge_cloud:v1.0
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    args: ["/bin/bash","-c","python3 cloud_socket.py -i 0.0.0.0 -p 99"]
    ports:
    - containerPort: 99
      protocol: TCP