FROM debian:buster-slim
USER root
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
RUN apt-get update && \
    apt-get install -y bash ca-certificates tzdata unzip
ENV TZ="Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
LABEL maintainer="Yang Guang <yangg.china@outlook.com>"

# 工作目录准备
WORKDIR /app

# 编译环境安装
RUN apt-get install -y python3 python3-pip git curl
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN apt-get install -y \
    wget \
    build-essential \
    gcc \
    g++ \
    make \
    zlib1g-dev \
    libffi-dev \
    e2fsprogs \
    pkg-config \
    flex \
    bison \
    perl \
    bc \
    openssl \
    libssl-dev \
    libelf-dev \
    libc6-dev \
    binutils \
    binutils-dev \
    libdwarf-dev \
    u-boot-tools \
    mtd-utils \
    gcc-arm-linux-gnueabi \
    cpio \
    device-tree-compiler \
    git \
    git-lfs \
    ruby \
    ccache \
RUN python3 -m pip install --user ohos-build
ENV PATH=~/.local/bin:$PATH
RUN pip3 install scons && \
    pip3 install pycryptodome && \
    pip3 install --upgrade --ignore-installed six && \
    pip3 install ecdsa
RUN wget https://repo.huaweicloud.com/harmonyos/compiler/gcc_riscv32/7.3.0/linux/gcc_riscv32-linux-7.3.0.tar.gz && tar -xvf gcc_riscv32-linux-7.3.0.tar.gz -C ~
ENV PATH=~/gcc_riscv32/bin:$PATH

# 启动命令
CMD ["bash", "-c", "while true; do echo 'Container is running'; sleep 60; done"]




