apiVersion: v1
kind: PersistentVolume
metadata:
  name: linklab-compilev2-xiuos-worker-init-pv
  namespace: linklab
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: linklab-compilev2-xiuos-worker-init
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/kaikai/new-linklab/linklab-ldc/nfs/data/compile-worker/xiuos-worker/init
    server: 10.214.131.107