apiVersion: v1
kind: PersistentVolume
metadata:
  name: linklab-compilev2-xiuos-worker-writespace.0-pv
  namespace: linklab
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: linklab-compilev2-xiuos-worker-writespace
  hostPath:
    path: /home/kaikai/new-linklab/linklab-ldc/nfs/data/compile-worker/xiuos-worker/writespace.0