version: '3.7'

services:

  device-service:
    container_name: device-service
    restart: unless-stopped
    image: registry.cn-hangzhou.aliyuncs.com/linklab/device-control-v2-device-service:v1.0
    volumes: 
        - ./config/config.json:/app/config/config.json:ro
        - ./log/gin.log:/app/log/gin.log
        - ./log/logrus.log:/app/log/logrus.log
    networks: 
        - device_control_v2

networks: 
    device_control_v2:
        external: 
            name: device_control_v2
        