apiVersion: v1
kind: PersistentVolume
metadata:
  name: linklab-compilev2-esp32idf-worker-init-pv
  namespace: linklab
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: linklab-compilev2-esp32idf-worker-init
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/gongkj/LDC/linklab-ldc-master/nfs/data/compile-worker/esp32idf-worker/init
    server: 192.168.232.128
