apiVersion: v1
kind: PersistentVolume
metadata:
  name: linklab-compilev2-esp32idf-worker-writespace.0-pv
  namespace: linklab
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: linklab-compilev2-esp32idf-worker-writespace
  hostPath:
    path: /home/gongkj/LDC/linklab-ldc-master/nfs/data/compile-worker/esp32idf-worker/writespace.0
