version: '3.7'

services:

    jlink-client:
        container_name: jlink-client
        restart: unless-stopped
        image: registry.cn-hangzhou.aliyuncs.com/linklab/device-control-v2-jlink-client:v1.0
        volumes: 
            - ./config/config.json:/app/config/config.json:ro
            - ./tmp:/app/tmp:rw
            - ./log:/app/log:rw
            - /dev:/dev:rw
        privileged: true
        networks: 
            - jlink_client

networks: 
    jlink_client: