version: '3.7'

services:

  login-authentication:
    container_name: login-authentication
    restart: unless-stopped
    image: registry.cn-hangzhou.aliyuncs.com/linklab/device-control-v2-login-authentication:v1.0
    volumes: 
        - ./config/config.json:/app/config/config.json:ro
        - ./log:/app/log
    ports: 
        - "8082:8082"
    networks: 
        - device_control_v2

networks: 
    device_control_v2:
        external: 
            name: device_control_v2