apiVersion: v1
kind: PersistentVolume
metadata:
  name: stan-server-data-1
  namespace: linklab
  labels:
    alicloud-pvname: stan-server-data-1
    storage-class: stan-server-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeAttributes:
      path: /nfs/data/stan/data-1
      server: 043944ae96-buv89.cn-hangzhou.nas.aliyuncs.com
      vers: '3'
    volumeHandle: stan-server-data-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  volumeMode: Filesystem