apiVersion: v1
kind: PersistentVolume
metadata:
  name: stan-server-data-pv-1
  namespace: linklab
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stan-server-data
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/home/kaikai/new-linklab/linklab-ldc/nfs/data/stan/data-1"
    server: 10.214.131.107