apiVersion: v1
kind: Pod
metadata:
  name: edge-build
  # namespace: linklab
  labels:
    app: edge-build
spec:
  restartPolicy: Never
  # imagePullSecrets:
  # - name: linklab-aliyun
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: DoesNotExist
  containers:
  - image: registry.cn-hangzhou.aliyuncs.com/linklab/edge-build:v2.0-beta
    name: edge-build
    imagePullPolicy: Always
    # env:
    # - name: POD_NAME
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.name
    # - name: NODE_NAME
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: spec.nodeName
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock